#!/usr/bin/env python3
"""
data/positions_db.py
─────────────────────────────────────────────────────────────────────────────
Full trade lifecycle journal. Captures every event from signal to settlement.

Tables:
    signals     — every signal generated (whether traded or not)
    orders      — every order placed with full metadata
    fills       — every fill event
    positions   — current open positions
    exits       — every exit event (TP/SL/time/manual)
    settlements — every Kalshi settlement
    events      — generic event log for anything else
"""

import sqlite3
import logging
import os
from datetime import datetime, timezone

log = logging.getLogger("kalshi_bot.positions_db")
DB_PATH = "/root/kalshi-bot-v2/data/positions.db"


def get_db():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db():
    conn = get_db()
    conn.executescript("""

    -- Every signal generated by any strategy
    CREATE TABLE IF NOT EXISTS signals (
        id              INTEGER PRIMARY KEY AUTOINCREMENT,
        signal_time     TEXT NOT NULL,
        ticker          TEXT NOT NULL,
        series          TEXT,           -- KXNBAPTS, KXNBAGAME, KXMVESPORTS etc
        category        TEXT,           -- prop, game, combo, tennis, mlb
        strategy        TEXT,           -- prop_nba, nba_fade, combo_moonshot etc
        side            TEXT,           -- yes/no
        price_cents     INTEGER,
        confidence      REAL,
        edge            REAL,
        hit_rate        REAL,
        reason          TEXT,           -- full reasoning string
        source          TEXT,           -- bot/manual
        acted_on        INTEGER DEFAULT 0,  -- 1 if order placed
        skip_reason     TEXT,           -- why skipped if not acted on
        created_at      TEXT DEFAULT (datetime('now'))
    );

    -- Every order placed
    CREATE TABLE IF NOT EXISTS orders (
        id              INTEGER PRIMARY KEY AUTOINCREMENT,
        order_id        TEXT UNIQUE,
        client_order_id TEXT,
        signal_id       INTEGER REFERENCES signals(id),
        ticker          TEXT NOT NULL,
        category        TEXT,
        strategy        TEXT,
        side            TEXT,
        price_cents     INTEGER,
        contracts       INTEGER,
        source          TEXT,           -- bot/manual
        order_time      TEXT,
        status          TEXT DEFAULT 'pending',  -- pending/resting/filled/cancelled/expired
        fill_time       TEXT,
        fill_price      INTEGER,
        time_to_fill_secs INTEGER,      -- seconds from order to fill
        created_at      TEXT DEFAULT (datetime('now'))
    );

    -- Every fill event
    CREATE TABLE IF NOT EXISTS fills (
        id              INTEGER PRIMARY KEY AUTOINCREMENT,
        fill_time       TEXT NOT NULL,
        ticker          TEXT NOT NULL,
        order_id        TEXT,
        side            TEXT,
        qty             INTEGER,
        fill_price      INTEGER,
        cost_basis      REAL,
        source          TEXT,
        strategy        TEXT,
        created_at      TEXT DEFAULT (datetime('now'))
    );

    -- Current open positions (upserted on fill, deleted on settlement)
    CREATE TABLE IF NOT EXISTS positions (
        id              INTEGER PRIMARY KEY AUTOINCREMENT,
        ticker          TEXT UNIQUE,
        order_id        TEXT,
        side            TEXT,
        qty             INTEGER,
        entry_price     INTEGER,
        cost_basis      REAL,
        source          TEXT,
        strategy        TEXT,
        category        TEXT,
        confidence      REAL,
        edge            REAL,
        hit_rate        REAL,
        reason          TEXT,
        entry_time      TEXT,
        peak_price      INTEGER,        -- highest yes_bid seen
        current_price   INTEGER,        -- last known price
        unrealized_pnl  REAL,
        created_at      TEXT DEFAULT (datetime('now'))
    );

    -- Exit events (TP/SL/time/manual)
    CREATE TABLE IF NOT EXISTS exits (
        id              INTEGER PRIMARY KEY AUTOINCREMENT,
        exit_time       TEXT NOT NULL,
        ticker          TEXT NOT NULL,
        order_id        TEXT,
        exit_reason     TEXT,           -- tp/sl/time/manual/settlement
        entry_price     INTEGER,
        exit_price      INTEGER,
        contracts       INTEGER,
        pnl             REAL,
        hold_time_mins  INTEGER,        -- minutes from entry to exit
        source          TEXT,
        strategy        TEXT,
        created_at      TEXT DEFAULT (datetime('now'))
    );

    -- Kalshi settlements
    CREATE TABLE IF NOT EXISTS settlements (
        id              INTEGER PRIMARY KEY AUTOINCREMENT,
        settled_time    TEXT NOT NULL,
        ticker          TEXT NOT NULL,
        category        TEXT,
        revenue         REAL,
        cost_basis      REAL,
        pnl             REAL,
        source          TEXT,
        strategy        TEXT,
        entry_price     INTEGER,
        confidence      REAL,
        edge            REAL,
        hit_rate        REAL,
        result          TEXT,           -- win/loss/void/scalar
        created_at      TEXT DEFAULT (datetime('now'))
    );

    -- Generic event log
    CREATE TABLE IF NOT EXISTS events (
        id              INTEGER PRIMARY KEY AUTOINCREMENT,
        event_time      TEXT NOT NULL,
        event_type      TEXT,           -- rfq_submitted, quote_received, etc
        ticker          TEXT,
        details         TEXT,           -- JSON blob
        created_at      TEXT DEFAULT (datetime('now'))
    );

    -- Indexes
    CREATE INDEX IF NOT EXISTS idx_signals_ticker    ON signals(ticker);
    CREATE INDEX IF NOT EXISTS idx_signals_strategy  ON signals(strategy);
    CREATE INDEX IF NOT EXISTS idx_signals_time      ON signals(signal_time);
    CREATE INDEX IF NOT EXISTS idx_orders_ticker     ON orders(ticker);
    CREATE INDEX IF NOT EXISTS idx_orders_status     ON orders(status);
    CREATE INDEX IF NOT EXISTS idx_fills_ticker      ON fills(ticker);
    CREATE INDEX IF NOT EXISTS idx_positions_source  ON positions(source);
    CREATE INDEX IF NOT EXISTS idx_settlements_source ON settlements(source);
    CREATE INDEX IF NOT EXISTS idx_settlements_time  ON settlements(settled_time);
    """)
    conn.commit()
    conn.close()
    log.info(f"[PositionsDB] Initialized")


# ── Writers ────────────────────────────────────────────────────────────────

def record_signal(ticker: str, strategy: str, side: str, price_cents: int,
                  confidence: float = 0, edge: float = 0, hit_rate: float = 0,
                  reason: str = '', source: str = 'bot', acted_on: bool = False,
                  skip_reason: str = '') -> int:
    """Record a signal. Returns signal_id."""
    series   = ticker.split('-')[0]
    category = _categorize(ticker)
    conn = get_db()
    try:
        cur = conn.execute("""
            INSERT INTO signals
            (signal_time, ticker, series, category, strategy, side,
             price_cents, confidence, edge, hit_rate, reason,
             source, acted_on, skip_reason)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        """, (now(), ticker, series, category, strategy, side,
              price_cents, confidence, edge, hit_rate, reason,
              source, int(acted_on), skip_reason))
        conn.commit()
        return cur.lastrowid
    finally:
        conn.close()


def record_order(order_id: str, client_order_id: str, ticker: str,
                 strategy: str, side: str, price_cents: int,
                 contracts: int, source: str = 'bot',
                 signal_id: int = None) -> int:
    """Record an order placement."""
    category = _categorize(ticker)
    conn = get_db()
    try:
        cur = conn.execute("""
            INSERT OR IGNORE INTO orders
            (order_id, client_order_id, signal_id, ticker, category,
             strategy, side, price_cents, contracts, source,
             order_time, status)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?)
        """, (order_id, client_order_id, signal_id, ticker, category,
              strategy, side, price_cents, contracts, source,
              now(), 'pending'))
        conn.commit()
        return cur.lastrowid
    finally:
        conn.close()


def record_fill(ticker: str, order_id: str, client_order_id: str,
                side: str, qty: int, fill_price: int,
                source: str = 'unknown', strategy: str = '',
                confidence: float = 0, edge: float = 0,
                hit_rate: float = 0, reason: str = ''):
    """Record a fill and open/update position."""
    cost_basis = qty * fill_price / 100.0
    category   = _categorize(ticker)
    fill_time  = now()
    conn = get_db()
    try:
        # Record fill
        conn.execute("""
            INSERT INTO fills
            (fill_time, ticker, order_id, side, qty,
             fill_price, cost_basis, source, strategy)
            VALUES (?,?,?,?,?,?,?,?,?)
        """, (fill_time, ticker, order_id, side, qty,
              fill_price, cost_basis, source, strategy))

        # Update order status + fill time
        conn.execute("""
            UPDATE orders SET status='filled', fill_time=?, fill_price=?
            WHERE order_id=?
        """, (fill_time, fill_price, order_id))

        # Upsert position
        conn.execute("""
            INSERT INTO positions
            (ticker, order_id, side, qty, entry_price, cost_basis,
             source, strategy, category, confidence, edge, hit_rate,
             reason, entry_time, peak_price, current_price, unrealized_pnl)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0)
            ON CONFLICT(ticker) DO UPDATE SET
                qty           = qty + excluded.qty,
                cost_basis    = cost_basis + excluded.cost_basis
        """, (ticker, order_id, side, qty, fill_price, cost_basis,
              source, strategy, category, confidence, edge,
              hit_rate, reason, fill_time, fill_price, fill_price))

        conn.commit()
        log.info(f"[PositionsDB] Fill: {ticker} {side} @ {fill_price}¢ "
                f"source={source} strategy={strategy}")
    except Exception as e:
        log.warning(f"[PositionsDB] Fill failed: {e}")
    finally:
        conn.close()


def record_settlement(ticker: str, revenue: float,
                      source: str = 'unknown', strategy: str = ''):
    """Record settlement and close position."""
    category    = _categorize(ticker)
    settled_at  = now()
    conn = get_db()
    try:
        # Get position data
        pos = conn.execute(
            "SELECT * FROM positions WHERE ticker=?", (ticker,)
        ).fetchone()

        cost_basis  = pos['cost_basis']  if pos else 0
        entry_price = pos['entry_price'] if pos else 0
        confidence  = pos['confidence']  if pos else 0
        edge        = pos['edge']        if pos else 0
        hit_rate    = pos['hit_rate']    if pos else 0
        src         = pos['source']      if pos else source
        strat       = pos['strategy']    if pos else strategy

        pnl    = revenue - cost_basis
        result = 'win' if revenue > cost_basis else 'loss' if revenue == 0 else 'scalar'

        conn.execute("""
            INSERT INTO settlements
            (settled_time, ticker, category, revenue, cost_basis, pnl,
             source, strategy, entry_price, confidence, edge, hit_rate, result)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)
        """, (settled_at, ticker, category, revenue, cost_basis, pnl,
              src, strat, entry_price, confidence, edge, hit_rate, result))

        # Remove closed position
        conn.execute("DELETE FROM positions WHERE ticker=?", (ticker,))

        conn.commit()
        log.info(f"[PositionsDB] Settlement: {ticker} "
                f"revenue=${revenue:.2f} pnl=${pnl:.2f} result={result}")
    except Exception as e:
        log.warning(f"[PositionsDB] Settlement failed: {e}")
    finally:
        conn.close()


def record_exit(ticker: str, order_id: str, exit_reason: str,
                entry_price: int, exit_price: int, contracts: int,
                pnl: float, source: str = 'bot', strategy: str = ''):
    """Record an exit event."""
    conn = get_db()
    try:
        # Calculate hold time
        pos = conn.execute(
            "SELECT entry_time FROM positions WHERE ticker=?", (ticker,)
        ).fetchone()
        hold_mins = 0
        if pos and pos['entry_time']:
            from datetime import datetime
            try:
                entry = datetime.fromisoformat(pos['entry_time'])
                hold_mins = int((datetime.now(timezone.utc) - entry).total_seconds() / 60)
            except Exception:
                pass

        conn.execute("""
            INSERT INTO exits
            (exit_time, ticker, order_id, exit_reason, entry_price,
             exit_price, contracts, pnl, hold_time_mins, source, strategy)
            VALUES (?,?,?,?,?,?,?,?,?,?,?)
        """, (now(), ticker, order_id, exit_reason, entry_price,
              exit_price, contracts, pnl, hold_mins, source, strategy))
        conn.commit()
    except Exception as e:
        log.warning(f"[PositionsDB] Exit record failed: {e}")
    finally:
        conn.close()


def log_event(event_type: str, ticker: str = '', details: dict = None):
    """Log a generic event."""
    import json
    conn = get_db()
    try:
        conn.execute("""
            INSERT INTO events (event_time, event_type, ticker, details)
            VALUES (?,?,?,?)
        """, (now(), event_type, ticker,
              json.dumps(details) if details else None))
        conn.commit()
    except Exception:
        pass
    finally:
        conn.close()


# ── Readers ────────────────────────────────────────────────────────────────

def get_open_positions(source: str = None) -> list:
    conn = get_db()
    try:
        if source:
            rows = conn.execute(
                "SELECT * FROM positions WHERE source=? ORDER BY entry_time DESC",
                (source,)
            ).fetchall()
        else:
            rows = conn.execute(
                "SELECT * FROM positions ORDER BY entry_time DESC"
            ).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


def get_pnl_summary() -> dict:
    conn = get_db()
    try:
        rows = conn.execute("""
            SELECT source,
                   COUNT(*)  as n,
                   SUM(CASE WHEN result='win' THEN 1 ELSE 0 END) as wins,
                   SUM(revenue)  as revenue,
                   SUM(pnl)      as pnl,
                   AVG(pnl)      as avg_pnl
            FROM settlements
            GROUP BY source
        """).fetchall()
        result = {}
        for r in rows:
            n = r['n'] or 1
            result[r['source']] = {
                'n':        r['n'],
                'wins':     r['wins'],
                'revenue':  round(r['revenue'] or 0, 2),
                'pnl':      round(r['pnl'] or 0, 2),
                'avg_pnl':  round(r['avg_pnl'] or 0, 2),
                'win_rate': round((r['wins'] or 0) / n * 100, 1),
            }
        return result
    finally:
        conn.close()


def get_strategy_performance() -> list:
    conn = get_db()
    try:
        rows = conn.execute("""
            SELECT strategy,
                   COUNT(*)   as n,
                   SUM(CASE WHEN result='win' THEN 1 ELSE 0 END) as wins,
                   SUM(pnl)   as total_pnl,
                   AVG(pnl)   as avg_pnl,
                   AVG(confidence) as avg_conf
            FROM settlements
            WHERE strategy != ''
            GROUP BY strategy
            ORDER BY total_pnl DESC
        """).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


def get_recent_settlements(limit: int = 20, source: str = None) -> list:
    conn = get_db()
    try:
        if source:
            rows = conn.execute(
                "SELECT * FROM settlements WHERE source=? ORDER BY settled_time DESC LIMIT ?",
                (source, limit)
            ).fetchall()
        else:
            rows = conn.execute(
                "SELECT * FROM settlements ORDER BY settled_time DESC LIMIT ?",
                (limit,)
            ).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


def get_signal_stats() -> dict:
    """How many signals generated vs acted on."""
    conn = get_db()
    try:
        row = conn.execute("""
            SELECT COUNT(*) as total,
                   SUM(acted_on) as acted,
                   COUNT(DISTINCT strategy) as strategies
            FROM signals
        """).fetchone()
        return dict(row) if row else {}
    finally:
        conn.close()


def get_fill_time_stats() -> dict:
    """Average time from order to fill."""
    conn = get_db()
    try:
        row = conn.execute("""
            SELECT AVG(time_to_fill_secs) as avg_secs,
                   MIN(time_to_fill_secs) as min_secs,
                   MAX(time_to_fill_secs) as max_secs,
                   COUNT(*) as n
            FROM orders
            WHERE status='filled' AND time_to_fill_secs IS NOT NULL
        """).fetchone()
        return dict(row) if row else {}
    finally:
        conn.close()


# ── Helpers ────────────────────────────────────────────────────────────────

def now() -> str:
    return datetime.now(timezone.utc).isoformat()[:19]


def _categorize(ticker: str) -> str:
    if 'MULTIGAME' in ticker or 'CROSSCATEGORY' in ticker:
        return 'combo'
    series = ticker.split('-')[0]
    if series in ('KXNBAPTS','KXNBAREB','KXNBAAST',
                  'KXNBA3PT','KXNBASTL','KXNBABLK'):
        return 'prop'
    if 'NBAGAME' in series or 'NBASPR' in series:
        return 'game'
    if 'ATP' in series or 'WTA' in series:
        return 'tennis'
    if 'MLB' in series:
        return 'mlb'
    return 'other'


init_db()
